anio: 2025
etapa: internacional
fuente: Olimpiada Latinoamericana de Astronomia y Astronautica 2025, Grupal
institucion: olimpiada-latinoamericana
subtemas:
- Espectroscopia
- Efecto Doppler
tema: astrofisica
