anio: 2025
dificultad: intermedio
etapa: nacional
fuente: Olimpiada Argentina de Astronomia 2025, Nacional
institucion: olimpiada-argentina
nivel: N1
numero: 2
subtemas:
- estrellas binarias
- magnitudes
- luminosidad
tema: astrofisica
