anio: 2020
etapa: nacional
fuente: Olimpiada Argentina de Astronomía 2020, Examen Final Nacional
institucion: olimpiada-argentina
modalidad: individual
nivel: N1
numero: 3
subtemas:
- longitud de onda
- espectro electromagnético
- frecuencia
tema: radiacion
