anio: 2023
dificultad: dificil
etapa: nacional
fuente: Olimpiada Argentina de Astronomía 2023, Examen Final Nacional
institucion: olimpiada-argentina
modalidad: individual
nivel: N2
numero: 3
solucion: http://oaa.oac.unc.edu.ar/wp-content/blogs.dir/8/files/sites/8/2023/11/Sol_D_FIN_2023.pdf
subtemas:
- tercera ley de kepler
- período orbital
tema: mecanica-celeste
