anio: 2023
etapa: nacional
fuente: Olimpiada Argentina de Astronomía 2023, Examen Final Nacional
institucion: olimpiada-argentina
modalidad: individual
nivel: N2
numero: 3
subtemas:
- tercera ley de kepler
- período orbital
- semieje mayor
tema: mecanica-celeste
