anio: 2024
dificultad: intermedio
etapa: nacional
fuente: Olimpiada Argentina de Astronomía 2024, Examen Final Nacional
institucion: olimpiada-argentina
modalidad: individual
nivel: N2
numero: 2
solucion: http://oaa.oac.unc.edu.ar/wp-content/blogs.dir/8/files/sites/8/2024/11/Sol_D_FIN_2024.pdf
subtemas:
- tamaño angular
- período orbital
- configuraciones planetarias
tema: mecanica-celeste
