anio: 2021
etapa: nacional
fuente: Olimpiada Argentina de Astronomía 2021, Examen Final Nacional
institucion: olimpiada-argentina
modalidad: individual
nivel: N1
numero: 2
subtemas:
- gravitación
- equilibrio gravitacional
tema: mecanica-celeste
