anio: 2023
etapa: nacional
fuente: Olimpiada Argentina de Astronomía 2023, Examen Final Nacional
institucion: olimpiada-argentina
modalidad: individual
nivel: N1
numero: 2
subtemas:
- luminosidad
- magnitud absoluta
- magnitud aparente
- ley de wien
tema: astrofisica
