anio: 2019
dificultad: facil
etapa: nacional
fuente: Olimpiada Argentina de Astronomía 2019, Examen Final Nacional
institucion: olimpiada-argentina
modalidad: individual
nivel: N1
numero: 1
solucion: http://oaa.oac.unc.edu.ar/wp-content/blogs.dir/8/files/sites/8/2019/11/Sol_D_FIN_2019.pdf
subtemas:
- órbitas circulares
- velocidad orbital
- velocidad de escape
tema: mecanica-celeste
