anio: 2024
etapa: nacional
fuente: Olimpiada Argentina de Astronomía 2024, Examen Final Nacional
institucion: olimpiada-argentina
modalidad: individual
nivel: N2
numero: 1
subtemas:
- estrellas cefeidas
- período-luminosidad
- distancia
- constante de Hubble
tema: astrofisica
