anio: 2021
etapa: nacional
fuente: Olimpiada Argentina de Astronomía 2021, Examen Final Nacional
institucion: olimpiada-argentina
modalidad: individual
nivel: N2
numero: 1
subtemas:
- manchas solares
- tamaño angular
- resolución angular
tema: astrofisica
