anio: 2024
etapa: internacional
fuente: Olimpiada Latinoamericana de Astronomia y Astronautica 2024, Individual
institucion: olimpiada-latinoamericana
subtemas:
- Relacion Tully-Fisher
- Magnitudes
solucion: https://drive.google.com/file/d/1WdGKjVIk5ScSs0ZAvSckJ_FPA63YMdEw/view
tema: galaxias
