anio: 2021
etapa: nacional
fuente: Olimpiada Argentina de Astronomía 2021, Examen Final Nacional
institucion: olimpiada-argentina
modalidad: individual
nivel: N2
numero: 3
subtemas:
- ángulo horario
- declinación
- latitud
- horas de luz
tema: coordenadas-celestes
