anio: 2023
dificultad: facil
etapa: nacional
fuente: Olimpiada Argentina de Astronomía 2023, Examen Final Nacional
institucion: olimpiada-argentina
modalidad: individual
nivel: N1
numero: 2
solucion: http://oaa.oac.unc.edu.ar/wp-content/blogs.dir/8/files/sites/8/2023/11/Sol_D_FIN_2023.pdf
subtemas:
- luminosidad
- magnitud absoluta
- magnitud aparente
- ley de wien
tema: radiacion
