anio: 2025
dificultad: dificil
etapa: internacional
fuente: Olimpiada Latinoamericana de Astronomia y Astronautica 2025, Grupal
institucion: olimpiada-latinoamericana
modalidad: grupal
numero: 2
solucion: https://drive.google.com/file/d/17126DEUbe8Aa1s0cWpYhI63OtTHca0F9/view?usp=sharing
subtemas:
- Exoplanetas
- Fotometria
tema: astrofisica
