anio: 2023
etapa: nacional
fuente: Olimpiada Argentina de Astronomía 2023, Examen Final Nacional
institucion: olimpiada-argentina
modalidad: individual
nivel: N2
numero: 2
subtemas:
- longitud geográfica
- tiempo sidéreo
- distancia angular
tema: coordenadas-celestes
