anio: 2020
dificultad: facil
etapa: nacional
fuente: Olimpiada Argentina de Astronomía 2020, Examen Final Nacional
institucion: olimpiada-argentina
modalidad: individual
nivel: N1
numero: 4
solucion: http://oaa.oac.unc.edu.ar/wp-content/blogs.dir/8/files/sites/8/2021/03/Sol_D_FIN_2020.pdf
subtemas:
- tercera ley de kepler
- masa planetaria
- órbitas
tema: mecanica-celeste
