anio: 2021
etapa: nacional
fuente: Olimpiada Argentina de Astronomía 2021, Examen Final Nacional
institucion: olimpiada-argentina
modalidad: individual
nivel: N2
numero: 2
subtemas:
- sistema binario
- magnitud absoluta
- curva de luz
tema: astrofisica
