anio: 2019
etapa: nacional
fuente: Olimpiada Argentina de Astronomía 2019, Examen Final Nacional
institucion: olimpiada-argentina
modalidad: individual
nivel: N1
numero: 1
subtemas:
- órbitas circulares
- velocidad orbital
- velocidad de escape
tema: mecanica-celeste
