anio: 2020
dificultad: facil
etapa: nacional
fuente: Olimpiada Argentina de Astronomía 2020, Examen Final Nacional
institucion: olimpiada-argentina
modalidad: individual
nivel: N2
numero: 5
solucion: http://oaa.oac.unc.edu.ar/wp-content/blogs.dir/8/files/sites/8/2021/03/Sol_D_FIN_2020.pdf
subtemas:
- radiación de fondo cósmico
- ley de wien
tema: radiacion
