anio: 2024
etapa: nacional
fuente: Olimpiada Argentina de Astronomía 2024, Examen Final Nacional
institucion: olimpiada-argentina
modalidad: individual
nivel: N2
numero: 4
subtemas:
- órbitas elípticas
- semieje mayor
- excentricidad
- segunda ley de kepler
tema: mecanica-celeste
