anio: 2020
etapa: nacional
fuente: Olimpiada Argentina de Astronomía 2020, Examen Final Nacional
institucion: olimpiada-argentina
modalidad: individual
nivel: N2
numero: 3
subtemas:
- sistema binario
- luminosidad
- temperatura
- radio estelar
tema: astrofisica
