anio: 2019
etapa: nacional
fuente: Olimpiada Argentina de Astronomía 2019, Examen Final Nacional
institucion: olimpiada-argentina
modalidad: individual
nivel: N2
numero: 5
subtemas:
- resolución angular
- interferometría
- radiotelescopio
tema: instrumentos
