anio: 2022
dificultad: intermedio
etapa: nacional
fuente: Olimpiada Argentina de Astronomía 2022, Examen Final Nacional
institucion: olimpiada-argentina
modalidad: individual
nivel: N1
numero: 4
solucion: http://oaa.oac.unc.edu.ar/wp-content/blogs.dir/8/files/sites/8/2023/08/Sol_D_FIN_2022.pdf
subtemas:
- azimut
- declinación
- ascensión recta
- ángulo horario
- latitud
tema: coordenadas-celestes
