anio: 2024
etapa: nacional
fuente: Olimpiada Argentina de Astronomía 2024, Examen Final Nacional
institucion: olimpiada-argentina
modalidad: individual
nivel: N2
numero: 3
subtemas:
- stefan-boltzmann
- ley de wien
- radio estelar
tema: astrofisica
