anio: 2023
etapa: nacional
fuente: Olimpiada Argentina de Astronomía 2023, Examen Final Nacional
institucion: olimpiada-argentina
modalidad: individual
nivel: N2
numero: 5
subtemas:
- luminosidad
- ley de wien
- magnitud absoluta
tema: astrofisica
