anio: 2025
dificultad: intermedio
etapa: nacional
fuente: Olimpiada Argentina de Astronomia 2025, Nacional
institucion: olimpiada-argentina
modalidad: individual
nivel: N1
numero: 4
subtemas:
- orbitas
- velocidad angular
tema: mecanica-celeste
