anio: 2024
etapa: nacional
fuente: Olimpiada Argentina de Astronomía 2024, Examen Final Nacional
institucion: olimpiada-argentina
modalidad: individual
nivel: N1
numero: 4
subtemas:
- magnitud aparente
- magnitud absoluta
- cúmulos estelares
tema: magnitudes
