anio: 2022
etapa: nacional
fuente: Olimpiada Argentina de Astronomía 2022, Examen Final Nacional
institucion: olimpiada-argentina
modalidad: individual
nivel: N2
numero: 2
subtemas:
- masa de aire
- extinción atmosférica
- magnitud
tema: instrumentos
