anio: 2019
dificultad: intermedio
etapa: nacional
fuente: Olimpiada Argentina de Astronomía 2019, Examen Final Nacional
institucion: olimpiada-argentina
modalidad: individual
nivel: N2
numero: 3
solucion: http://oaa.oac.unc.edu.ar/wp-content/blogs.dir/8/files/sites/8/2019/11/Sol_D_FIN_2019.pdf
subtemas:
- manchas solares
- velocidad angular
tema: astrofisica
